language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - bin/phpunit --group read-only test

notifications:
  slack: traackr:uCvPkzPufVG9zKPpIu5AtG7M