language: php
php:
- 5.5
- 5.6
before_script:
- wget http://getcomposer.org/composer.phar
- php composer.phar install
script:
- bin/phpunit --group read-only test
notifications:
  slack: traackr:uCvPkzPufVG9zKPpIu5AtG7M
env:
  global:
    secure: ggYYwf4JEVf3zq/CwlWmelxJ9Dpyf4hGMAvhoCN1qT9el8HjNJCMceMNTc30WBFdwgnaFPA2JlFW2a6Ocyy19x4ydY7BYu/f26EZ1YI6BvNtUDTWhI3t5FnldQUsiJx5ce6xHnBn2ofKuMopw/dDI8MoLIjuTWhk3O4APJci+FM=
