language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
before_script:
- wget http://getcomposer.org/composer.phar
- php composer.phar install
script:
- bin/phpunit --group read-only test
notifications:
  slack: traackr:uCvPkzPufVG9zKPpIu5AtG7M
env:
  global:
  - secure: LARPzUAGFcCqta7NZrymyknBUrJYmdKoTF+qNW9wBuS3iuGiYEBJHqIJy7M2e6pRe0kHPjrqZmz1FSd1RL2Nz7q974G6b9GOa/cNm6jIyEmc0wDZFR/dlPZWGTZWS8SNZLXXV5CSK3W1XwMeW1ZhIbcGw80Ef0EfsCNFqR+mbj8=
